build:
  server-netcore-build:
    path: "server-netcore/"
    watch: "*.cs"
    command: "cd server-netcore && dotnet publish server-netcore.csproj -c Release -o /tmp/demo/builds/server-netcore/publish"
    delay: 3
    timeout: 60
    stopStrings:
      - "The operation was canceled"
  server-node-install:
    path: "server-node/"
    watch: "*.js"
    command: "cd server-node && npm install"
    delay: 3
    timeout: 60
    stopStrings:
      - "The operation was canceled"
  server-python-install:
    path: "server-python/"
    watch: "*.py"
    command: "cd server-python && pip install -r requirements.txt"
    delay: 3
    timeout: 60
    stopStrings:
      - "The operation was canceled"
  client-svelte-build:
    path: "client-svelte/"
    watch: "*.ts *.js *.json *.svelte *.css *.html"
    command: "cd client-svelte && npm install && npm run build"
    delay: 3
    timeout: 120
    stopStrings:
      - "The operation was canceled"
  client-react-build:
    path: "client-react/"
    watch: "*.ts *.tsx *.js *.jsx *.json *.css *.html"
    command: "cd client-react && npm install && npm run build"
    delay: 3
    timeout: 120
    stopStrings:
      - "The operation was canceled"
